package com.routing.engine.constants;

public class MessageConstants {
	public static final String REDIS_TEST_DATA = "[\r\n"
			+ "    {\r\n"
			+ "\r\n"
			+ "\"user_id\":\"2345654e3wytuiop\",\r\n"
			+ "\r\n"
			+ "            \"active_chat_count\": 50,\r\n"
			+ "\r\n"
			+ "            \"status\": \"Available\",\r\n"
			+ "\r\n"
			+ "            \"last_chat_end_time\": \"2022-11-17T05:13:30.161Z\",\r\n"
			+ "\r\n"
			+ "            \"total_ongoing\": 4,\r\n"
			+ "\r\n"
			+ "            \"total_completed\": 5,\r\n"
			+ "            \"language\":\"Tamil\",\r\n"
			+ "            \"skill_group\":\"Banking\"\r\n"
			+ "\r\n"
			+ "        },\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "   {\r\n"
			+ "\r\n"
			+ "            \"user_id\":\"2345654e3wytuioqqp\",\r\n"
			+ "\r\n"
			+ "            \"active_chat_count\": 50,\r\n"
			+ "\r\n"
			+ "            \"status\": \"Available\",\r\n"
			+ "\r\n"
			+ "            \"last_chat_end_time\": \"2022-11-17T05:13:20.161Z\",\r\n"
			+ "\r\n"
			+ "            \"total_ongoing\": 2,\r\n"
			+ "\r\n"
			+ "            \"total_completed\": 5,\r\n"
			+ "            \"language\":\"Tamil\",\r\n"
			+ "            \"skill_group\":\"Banking\"\r\n"
			+ "\r\n"
			+ "       },\r\n"
			+ "\r\n"
			+ " {\r\n"
			+ "\r\n"
			+ "            \"user_id\":\"2345654e3wytuioqqp\",\r\n"
			+ "\r\n"
			+ "            \"active_chat_count\": 50,\r\n"
			+ "\r\n"
			+ "            \"status\": \"Available\",\r\n"
			+ "\r\n"
			+ "            \"last_chat_end_time\": \"2022-11-17T05:13:35.161Z\",\r\n"
			+ "\r\n"
			+ "            \"total_ongoing\": 1,\r\n"
			+ "\r\n"
			+ "            \"total_completed\": 5,\r\n"
			+ "            \"language\":\"Tamil\",\r\n"
			+ "            \"skill_group\":\"Banking\"\r\n"
			+ "\r\n"
			+ "        }]";
	
	public static final String REDIS_TEST_DATA_VERSION2 = "[\r\n"
			+ "   {\r\n"
			+ "    \"firstName\": \"system\",\r\n"
			+ "    \"lastName\": \"admin\",\r\n"
			+ "    \"mobileNumber\": 123456789,\r\n"
			+ "    \"email\": \"test@gmail.com\",\r\n"
			+ "    \"userId\": \"12212\",\r\n"
			+ "    \"roles\": [],\r\n"
			+ "    \"groups\": [],\r\n"
			+ "    \"language\": [{\r\n"
			+ "            \"language\": \"Tamil\",\r\n"
			+ "            \"proficiency\": \"Proficient\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"language\": \"Hindi\",\r\n"
			+ "            \"proficiency\": \"Intermediate\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"skillSet\": [{\r\n"
			+ "        \"skill\": \"Banking\",\r\n"
			+ "        \"proficiency\": \"Intermediate\"\r\n"
			+ "    }],\r\n"
			+ "    \"status\": \"Available\",\r\n"
			+ "    \"chat\": {\r\n"
			+ "        \"active_chat_count\": 34,\r\n"
			+ "        \"total_ongoing\": 2,\r\n"
			+ "        \"total_completed\": 22,\r\n"
			+ "        \"last_chat_time \": \"\",\r\n"
			+ "        \"last_chat_end_time\": \"2022-11-15T04:40:15.550Z\"\r\n"
			+ "    }\r\n"
			+ "},\r\n"
			+ "{\r\n"
			+ "    \"firstName\": \"system\",\r\n"
			+ "    \"lastName\": \"admin\",\r\n"
			+ "    \"mobileNumber\": 123456789,\r\n"
			+ "    \"email\": \"test@gmail.com\",\r\n"
			+ "    \"userId\": \"df2feee6-795d-4d03-880d-fa088137d2b8\",\r\n"
			+ "    \"roles\": [],\r\n"
			+ "    \"groups\": [],\r\n"
			+ "    \"language\": [{\r\n"
			+ "            \"language\": \"Arabic\",\r\n"
			+ "            \"proficiency\": \"Proficient\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"language\": \"Hindi\",\r\n"
			+ "            \"proficiency\": \"Intermediate\"\r\n"
			+ "        }\r\n"
			+ "    ],\r\n"
			+ "    \"skillSet\": [{\r\n"
			+ "        \"skill\": \"Customer Service\",\r\n"
			+ "        \"proficiency\": \"Intermediate\"\r\n"
			+ "    }],\r\n"
			+ "    \"status\": \"Available\",\r\n"
			+ "    \"chat\": {\r\n"
			+ "        \"active_chat_count\": 34,\r\n"
			+ "        \"total_ongoing\": 34,\r\n"
			+ "        \"total_completed\": 22,\r\n"
			+ "        \"last_chat_time \": \"\",\r\n"
			+ "        \"last_chat_end_time\": \"2022-11-15T04:40:14.550Z\"\r\n"
			+ "    }\r\n"
			+ "}]";
	}
